### ISSUE TITLE
Not working with Rails 4.02 and ruby 2.1

### ISSUE THREAD

**Issue by techverx** [edgarjs/ajaxful-rating#98]
rails g ajaxful_rating user generates the following errors.

faizan@faizan-HP-EliteBook-8440p:~/projects/movies_store$ rails generate ajaxful_rating user
/home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require': /home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/ajaxful_rating-2.2.9.1/lib/axr/model.rb:23: syntax error, unexpected ',', expecting => (SyntaxError)
/home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/ajaxful_rating-2.2.9.1/lib/axr/model.rb:27: syntax error, unexpected keyword_do_block, expecting keyword_end
      options[:dimensions].each do |dimension|
                                  ^
/home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/ajaxful_rating-2.2.9.1/lib/axr/model.rb:28: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
        has_many "#{dimension}_rates", :dependent => :destroy,
                  ^
/home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/ajaxful_rating-2.2.9.1/lib/axr/model.rb:28: syntax error, unexpected ',', expecting keyword_end
        has_many "#{dimension}_rates", :dependent => :destroy,
                                      ^
/home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/ajaxful_rating-2.2.9.1/lib/axr/model.rb:29: syntax error, unexpected ',', expecting keyword_end
...{:dimension => dimension.to_s}, :class_name => 'Rate', :as =...
...                               ^
/home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/ajaxful_rating-2.2.9.1/lib/axr/model.rb:29: syntax error, unexpected ',', expecting keyword_end
...n.to_s}, :class_name => 'Rate', :as => :rateable
...                               ^
/home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/ajaxful_rating-2.2.9.1/lib/axr/model.rb:93: syntax error, unexpected keyword_do_block, expecting keyword_end
...esent? or (v == false) }.map do |k, v|
...                               ^
/home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/ajaxful_rating-2.2.9.1/lib/axr/model.rb:93: syntax error, unexpected '|', expecting '='
/home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/ajaxful_rating-2.2.9.1/lib/axr/model.rb:192: syntax error, unexpected keyword_end, expecting end-of-input
    from /home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in`block in require'
    from /home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
    from /home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in`require'
    from /home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/ajaxful_rating-2.2.9.1/lib/ajaxful_rating.rb:3:in `<top (required)>'
    from /home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/bundler-1.5.1/lib/bundler/runtime.rb:76:in`require'
    from /home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/bundler-1.5.1/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/bundler-1.5.1/lib/bundler/runtime.rb:72:in`each'
    from /home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/bundler-1.5.1/lib/bundler/runtime.rb:72:in `block in require'
    from /home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/bundler-1.5.1/lib/bundler/runtime.rb:61:in`each'
    from /home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/bundler-1.5.1/lib/bundler/runtime.rb:61:in `require'
    from /home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/bundler-1.5.1/lib/bundler.rb:131:in`require'
    from /home/faizan/projects/movies_store/config/application.rb:7:in `<top (required)>'
    from /home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/railties-4.0.2/lib/rails/commands.rb:43:in`require'
    from /home/faizan/.rvm/gems/ruby-2.1.0@volen/gems/railties-4.0.2/lib/rails/commands.rb:43:in `<top (required)>'
    from bin/rails:4:in`require'
    from bin/rails:4:in `<main>'

**Comment by cis-sapna-v** [comment]
I am facing the same issue when I have upgrade my site rails 3 to rails 4. Is this gem is not compatible with rails 4. any suggestions?

**Comment by sungwoncho** [comment]
Any suggestions?
